// import generateInputData from './helpers/generate_input_data';

/**
 * This function takes data generated by `generateInputData` and sends it to the backend for processing.
 * Then, it outputs the processed results together with a loading indicator.
 * isLoading must be true the whole time until the data is returned from the backend.
 *
 * @returns {{ neighborhoods: Neighborhood[], isLoading: boolean }}
 */
function useData() {
    // const inputData = generateInputData();

    // TODO: Implement this function, check the backend to see where to send the data and how the response looks like

    const neighborhoods = [];
    const isLoading = true;
    return { neighborhoods, isLoading };
}

export default useData;
